const menuToggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
if(menuToggle&&nav){menuToggle.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));if(open){nav.removeAttribute('style');return;}Object.assign(nav.style,{display:'flex',position:'absolute',top:'50px',left:'11px',right:'11px',padding:'12px',background:'#fff',border:'1px solid #dbe7eb',borderRadius:'10px',flexDirection:'column',boxShadow:'0 10px 26px rgba(6,45,70,.12)'});});}

const animateNumber=(el,from,to,duration,formatter)=>{const start=performance.now();const frame=now=>{const p=Math.min((now-start)/duration,1);const eased=1-Math.pow(1-p,3);el.textContent=formatter(from+(to-from)*eased);if(p<1)requestAnimationFrame(frame);};requestAnimationFrame(frame);};

const choices=[...document.querySelectorAll('.choice-card')];
const problem=document.querySelector('.problem-section');
if(problem&&choices.length===3){let ran=false;const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting||ran)return;ran=true;const active=i=>choices.forEach((card,j)=>card.classList.toggle('is-active',i===j));active(0);setTimeout(()=>active(1),900);setTimeout(()=>active(2),1800);obs.unobserve(entry.target);});},{threshold:.3});obs.observe(problem);}

const maths=document.querySelector('.maths-section');
const equation=document.querySelector('.equation');
const growth=document.querySelector('.growth-strip');
if(maths&&equation&&growth){let ran=false;const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting||ran)return;ran=true;const steps=[equation.querySelector('.buyer'),equation.querySelector('.loan'),equation.querySelector('.boost'),equation.querySelector('.home')];const vals=steps.map(s=>s.querySelector('strong'));vals[0].textContent='$0k';vals[1].textContent='$0k';vals[2].textContent='$0k';vals[3].textContent='$0m';steps.forEach(s=>s.classList.remove('active-step'));steps[0].classList.add('active-step');animateNumber(vals[0],0,100,360,v=>'$'+Math.round(v)+'k');setTimeout(()=>{steps[0].classList.remove('active-step');steps[1].classList.add('active-step');animateNumber(vals[1],0,800,450,v=>'$'+Math.round(v)+'k');},450);setTimeout(()=>{steps[1].classList.remove('active-step');steps[2].classList.add('active-step');animateNumber(vals[2],0,100,360,v=>'$'+Math.round(v)+'k');},980);setTimeout(()=>{steps[2].classList.remove('active-step');steps[3].classList.add('active-step');animateNumber(vals[3],0,1,420,v=>'$'+v.toFixed(2).replace(/\.00$/,'')+'m');},1450);setTimeout(()=>{steps[3].classList.remove('active-step');growth.classList.add('is-animated');const gv=growth.querySelector('.growth-value');const start=1000000,finish=start*Math.pow(1.055,5);gv.textContent='$1.00m';animateNumber(gv,start,finish,1200,v=>'$'+(v/1000000).toFixed(2)+'m');},1970);obs.unobserve(entry.target);});},{threshold:.35});obs.observe(maths);}